#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Generate mesh
helyxRun blockMesh

# Create inlet/outlet patches
helyxRun topoSet -dict system/topoSetDict.faces
helyxRun createPatch -overwrite

# Create subset mesh
helyxRun -log log.topoSetDictSubset topoSet -dict system/topoSetDict.cells
helyxRun subsetMesh subsetCells -overwrite -patch fixedWalls

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch rightAngledDuct.foam

#------------------------------------------------------------------------------
