#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $HELYX_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0/polyMesh > /dev/null 2>&1
rm system/topoSetDict > /dev/null 2>&1

#------------------------------------------------------------------------------
