#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

# tags: asan

#------------------------------------------------------------------------------

mkdir -p constant/triSurface
cp $HELYX_TUTORIALS/resources/geometry/ahmed_body.stl.gz constant/triSurface/

# Mesh in parallel
helyxRun blockMesh
helyxRun decomposePar
helyxRun helyxHexMesh

# Setup
helyxRun caseSetup

# Map fields from coarse case
helyxRun helyxMap 

# Run
helyxRun helyxSolve

touch Ahmed25degFine.foam