#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Create mesh
helyxRun blockMesh

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Setup case for passive scalar transport simulation
# replaces previous scalarTransportFoam tutorial
helyxRun -log log.caseSetup.scalarTransport caseSetup -dict system/caseSetupDict.restart -latestTime

# Run passive scalar transport
helyxRun -log log.helyxSolve.scalarTransport helyxSolve

# Create dummy file for ParaView visualisation
touch pitzDaily.foam

#------------------------------------------------------------------------------
