#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Mesh
helyxRun blockMesh
helyxRun helyxHexMesh -overwrite

# Renumber the mesh to improve matrix solving
helyxRun renumberMesh -overwrite

# Create patches
helyxRun createPatch -overwrite

# Mesh report
helyxRun checkMesh -writeAllMetrics -latestTime
helyxRun postProcess -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )'

# Create dummy file for ParaView visualisation
touch box.foam

#------------------------------------------------------------------------------
