#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Create mesh
helyxRun blockMesh

# Setup
helyxRun caseSetup
helyxRun setFields

# Run
helyxRun helyxSolve

# Post-process
helyxRun -l log.postProcess.sample postProcess -func sample

# Create dummy file for ParaView visualisation
touch shockTube.foam

#------------------------------------------------------------------------------
