#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Create mesh
helyxRun blockMesh

# Create face zone for coupled patch
helyxRun topoSet

# Extrude pyrolysis region
helyxRun extrudeToRegionMesh -overwrite

# Setup the case
helyxRun caseSetup

# Setup reacting cloud postions (can it be set in caseSetup?)
cp system/reactingCloud1Positions constant/reactingCloud1Positions

# Create dummy file for paraview
touch simplePMMApanel.foam

# Run solver specified in controlDict
helyxRun

# -----------------------------------------------------------------------------
