#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

# Create mesh
helyxRun blockMesh

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch prism.foam

#------------------------------------------------------------------------------
