#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/cylinderAdjustFlowPFix/* constant/triSurface/

# Background mesh
helyxRun blockMesh

# Mesh
helyxRun helyxHexMesh

# Check
helyxRun checkMesh -allRegions -writeAllMetrics -latestTime

# Postprocess
helyxRun postProcess -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )' -dict system/controlDict.mesh

# Decomposition
helyxRun decomposePar -force

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch cylinderAdjustFlowPFix.foam

#------------------------------------------------------------------------------