#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/ahmed_body.stl.gz constant/triSurface/

# Background mesh
helyxRun blockMesh

# Decompose
helyxRun decomposePar

# Mesh in parallel
helyxRun helyxHexMesh

# Setup
helyxRun caseSetup

# Run solver specified in controlDict
helyxRun

# Create dummy file for ParaView visualisation
touch Ahmed25deg.foam

#------------------------------------------------------------------------------
