#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surfaces from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/iliacBifurcation/* constant/triSurface/

# Mesh and setup in parallel
helyxRun -p helyxHexMesh
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch iliacBifurcation.foam

#------------------------------------------------------------------------------
