#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Generate mesh
helyxRun blockMesh

# Create face and cell sets
helyxRun topoSet

# Refine mesh over a cell set
helyxRun refineHexMesh c0 -overwrite

# Decompose
helyxRun decomposePar -cellDist

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Reconstruct fields
helyxRun -serial reconstructPar

# Create dummy file for ParaView visualisation
touch pipeCyclic.foam

#------------------------------------------------------------------------------
