#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

# tags: asan

#------------------------------------------------------------------------------

# Source tutorial run functions
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

# Background mesh in series
helyxRun blockMesh

# Run topoSet
helyxRun topoSet

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualization
touch caa1dSinusoidalWave.foam

#------------------------------------------------------------------------------
