#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy STL file
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/GIBgeometries/mixer.stl constant/triSurface/

# Mesh in serial
helyxRun blockMesh

# Decompose mesh
helyxRun decomposePar

# Create GIB interface
helyxRun modifyGIBBoundary -addGIB

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch twoBladeMixer.foam

#------------------------------------------------------------------------------
