#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/motorBike.obj.gz constant/triSurface/

# Extract feature edges
helyxRun surfaceFeatureExtract

# Mesh
helyxRun blockMesh
helyxRun helyxHexMesh -overwrite

# Decomposition
helyxRun decomposePar -latestTime

# Check mesh quality
helyxRun checkMesh -writeAllMetrics -latestTime
helyxRun postProcess  -fields "(aspectRatio determinant nonOrthogonality skewness volumeRatio)" -dict system/controlDict.mesh
helyxRun patchSummary

# Create dummy file for ParaView visualization
touch motorBike.foam

#------------------------------------------------------------------------------
