#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Background mesh in series
helyxRun blockMesh

# Setup
helyxRun caseSetup

# Set fields
helyxRun setFields

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch hotRoom.foam

#------------------------------------------------------------------------------
