#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

helyxRun  blockMesh
helyxRun caseSetup
helyxRun -l log.helyxSolve.preProcess helyxSolve -postProcess -dict system/preProcess
helyxRun decomposePar
helyxRun

# Create dummy file for ParaView visualisation
touch rutlandVortex2D.foam

#------------------------------------------------------------------------------
