#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication $(getApplication)
runApplication -s sigma        postProcess -func "components(sigma)"
runApplication -s singleGraph  postProcess -func singleGraph

#------------------------------------------------------------------------------
