#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/F1FrontWing/* constant/triSurface/

# Background mesh
helyxRun blockMesh

# Decompose and mesh
helyxRun decomposePar
helyxRun helyxHexMesh

# Check mesh quality
helyxRun checkMesh -writeAllMetrics -latestTime
helyxRun postProcess -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )'

# Create dummy file for ParaView visualization
touch F1FrontWing.foam

#------------------------------------------------------------------------------
