#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp $HELYX_TUTORIALS/resources/geometry/chamber.stl.gz constant/triSurface/
cp $HELYX_TUTORIALS/resources/geometry/ovoid.stl.gz constant/triSurface/

# Create mesh for fluid and solid regions
helyxRun -parallel -l log.helyxHexMesh.default helyxHexMesh -region default
helyxRun -parallel -l log.helyxHexMesh.solid helyxHexMesh -region solid

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch ovoidRadiationSteadyNonConforming.foam

#------------------------------------------------------------------------------
