#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $HELYX_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f 0/enstrophy
mv 0/U.orig 0/U

#------------------------------------------------------------------------------
