#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

# Serial
#runApplication $(getApplication)

# Parallel
runApplication decomposePar -cellDist
runParallel $(getApplication)

#------------------------------------------------------------------------------
