#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Prepare mesh
helyxRun  blockMesh

# Setup case
helyxRun caseSetup

# Run the solver
helyxRun

# Create dummy file for ParaView visualisation
touch squareBendLiq.foam

#------------------------------------------------------------------------------
