#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

./Allrun.pre

runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar

# A bit more testing of decomposing
\cp system/controlDict_nextWrite system/controlDict
runParallel -s decompose redistributePar -decompose -latestTime
runParallel -s restart $(getApplication)

# -----------------------------------------------------------------------------
