#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails


# Copy bullet surface from resources directory
mkdir -p constant/triSurface
cp $HELYX_TUTORIALS/resources/geometry/bullet.stl.gz constant/triSurface/

helyxRun blockMesh
helyxRun decomposePar
helyxRun helyxHexMesh -overwrite
helyxRun caseSetup
helyxRun

#------------------------------------------------------------------------------
