#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

helyxRun blockMesh
helyxRun decomposePar
helyxRun helyxHexMesh -overwrite
helyxRun checkMesh -allRegions -writeAllMetrics -latestTime
helyxRun postProcess -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )' -dict system/controlDict.mesh
helyxRun caseSetup
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch channelWithLumpedBCs.foam

#------------------------------------------------------------------------------
