#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/flange.stl.gz constant/triSurface/

# Mesh
helyxRun helyxHexMesh

# Mesh report
helyxRun checkMesh -writeAllMetrics -latestTime
helyxRun postProcess -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )'

# Create dummy file for ParaView visualisation
touch flange.foam

#------------------------------------------------------------------------------
