#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $HELYX_PROJECT_DIR/bin/tools/CleanFunctions

(
    cd hopperInitialState || exit 1

    cleanCase
)

(
    cd hopperEmptying || exit 1

    cleanCase
    rm -rf 0
)

#------------------------------------------------------------------------------
