#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory

#------------------------------------------------------------------------------

helyxClean

rm -rf constant

rm system/compressibleGasGRI system/reactionsGRI

#------------------------------------------------------------------------------
