#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surfaces from resources directory
mkdir -p constant/triSurface
cp $HELYX_TUTORIALS/resources/geometry/AEC/* constant/triSurface/

# Create mesh
helyxRun -parallel helyxHexMesh

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Setup case for disperse Eulerian simulation
helyxRun -log log.caseSetup.disperseEulerian caseSetup -dict system/caseSetupDict.restart -latestTime

# Run disperse Eulerian
helyxRun -log log.helyxSolve.disperseEulerian helyxSolve

# Create dummy file for ParaView visualisation
touch windDrivenRain.foam

#------------------------------------------------------------------------------
