#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# copy flange surface from resources directory
mkdir -p constant/triSurface
cp $HELYX_TUTORIALS/resources/geometry/triangle/tri.stl constant/triSurface/

helyxRun -p helyxHexMesh

#------------------------------------------------------------------------------
