#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory

#------------------------------------------------------------------------------

helyxClean

rm -rf 0
rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/triSurface

#------------------------------------------------------------------------------
