# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BUILD_SOURCE_DIRS "@HELYX_PROJECT_DIR@;@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@")
set(CPACK_CMAKE_GENERATOR "@CPACK_CMAKE_GENERATOR@")
set(CPACK_COMPONENTS_ALL "@CPACK_COMPONENTS_ALL@")
set(CPACK_COMPONENT_INCLUDE_TOPLEVEL_DIRECTORY "0")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "ENGYS Ltd.")
set(CPACK_GENERATOR "@CPACK_GENERATOR@")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "0")
set(CPACK_INSTALL_CMAKE_PROJECTS "@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@;@CMAKE_PROJECT_NAME@;ALL;/")
set(CPACK_INSTALL_PREFIX "@CMAKE_INSTALL_PREFIX@")
set(CPACK_MODULE_PATH "@HELYX_PROJECT_DIR@/etc/cmake/findModules")
set(CPACK_OUTPUT_CONFIG_FILE "@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")

set(CPACK_PACKAGE_DESCRIPTION "Binary package for @HELYX_DIR_NAME@")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "@CMAKE_PROJECT_NAME@ built using CMake")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION "HELYXcore built using CMake")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "HELYXcore built using CMake")

set(CPACK_PACKAGE_DIRECTORY "@CPACK_PACKAGE_DIRECTORY@")
set(CPACK_PACKAGE_FILE_NAME "@HELYX_DIR_NAME@")
#set(CPACK_PACKAGE_FILE_NAME "@CMAKE_PROJECT_NAME@-@HELYX_PROJECT_VERSION@")
#set(CPACK_PACKAGE_FILE_NAME "@HELYX_PACKAGE_NAME@-@module_name@-@HELYX_PROJECT_VERSION@-SRC")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "@CMAKE_PROJECT_NAME@ @HELYX_PROJECT_VERSION@")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "@CMAKE_PROJECT_NAME@ @HELYX_PROJECT_VERSION@")
set(CPACK_PACKAGE_NAME "@CMAKE_PROJECT_NAME@")
set(CPACK_PACKAGE_VERSION "@HELYX_PROJECT_VERSION@")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SYSTEM_NAME "@CPACK_SYSTEM_NAME@")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "@CPACK_SYSTEM_NAME@")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
