# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BUILD_SOURCE_DIRS "@HELYX_PROJECT_DIR@;@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@")
set(CPACK_CMAKE_GENERATOR "@CPACK_CMAKE_GENERATOR@")
set(CPACK_COMPONENTS_ALL "@CPACK_COMPONENTS_ALL@")
#set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_INCLUDE_TOPLEVEL_DIRECTORY "0")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "ENGYS Ltd.")
set(CPACK_GENERATOR "@CPACK_GENERATOR@")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "0")
set(CPACK_IGNORE_FILES "@CPACK_IGNORE_FILES@")
set(CPACK_INSTALLED_DIRECTORIES "@CPACK_INSTALLED_DIRECTORIES@")
set(CPACK_INSTALL_PREFIX "@CMAKE_INSTALL_PREFIX@")
set(CPACK_MODULE_PATH "@HELYX_PROJECT_DIR@/etc/cmake/findModules")
set(CPACK_OUTPUT_CONFIG_FILE "@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@/CPackSourcesConfig-@module_name@.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DIRECTORY "@CPACK_PACKAGE_DIRECTORY@")


set(CPACK_PACKAGE_DESCRIPTION "Source package for @HELYX_DIR_NAME@")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "@CMAKE_PROJECT_NAME@ built using CMake")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION "HELYXcore built using CMake")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "HELYXcore built using CMake")


set(CPACK_PACKAGE_FILE_NAME "@CPACK_PACKAGE_FILE_NAME@")
set(CPACK_PACKAGE_NAME "@CMAKE_PROJECT_NAME@")
set(CPACK_PACKAGE_VERSION "@HELYX_PROJECT_VERSION@")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_ZIP "@CPACK_GENERATOR@")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "@CPACK_SYSTEM_NAME@")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "@CPACK_SYSTEM_NAME@")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "@HELYX_PROJECT_DIR@/cbuild/@HELYX_OPTIONS@_@HELYX_MPI_NAME@/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()

set(CPACK_PRE_BUILD_SCRIPTS "@CPACK_PRE_BUILD_SCRIPTS@")
