#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp $HELYX_TUTORIALS/resources/geometry/brakeDisk/* constant/triSurface/

# Mesh in parallel
helyxRun -parallel helyxHexMesh -overwrite

# Split mesh into multiple regions
helyxRun splitMeshRegions -overwrite -zoneToRegionMap '( (pad1 (pad1)) (pad2 (pad2)) (disk (disk)) )'

# Setup
helyxRun caseSetup

# Re-balance the mesh
helyxRun redistributePar -allRegions -overwrite

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch brakeDisk.foam

#------------------------------------------------------------------------------
