#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy geometry
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/splitSphere/* constant/triSurface/

# Create mesh
helyxRun blockMesh

# Decompose the mesh
helyxRun decomposePar

# Snap the mesh
helyxRun helyxHexMesh -overwrite

# Setup
helyxRun caseSetup

# Run the solver
helyxRun

# Create relative humidity field
helyxRun relativeHumidity

# Create dummy file for ParaView visualisation
touch mistCoolingSpray.foam

#------------------------------------------------------------------------------
