#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/windTunnel/* constant/triSurface/

# Mesh
helyxRun -parallel helyxHexMesh -overwrite

# Move mesh
helyxRun moveDynamicMesh -checkAMI

# Check
helyxRun checkMesh -writeAllMetrics -latestTime

# Run post-processing
helyxRun postProcess -field nonOrthogonality -latestTime

# Create dummy file for ParaView visualization
touch windTunnelRotation.foam

#------------------------------------------------------------------------------
