#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/serverRoom/* constant/triSurface/

helyxRun blockMesh
helyxRun decomposePar
helyxRun helyxHexMesh -overwrite
helyxRun caseSetup
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch serverRoom.foam

#------------------------------------------------------------------------------
