/*---------------------------------------------------------------------------*\
|       o        |
|    o     o     |  HELYX (R) : Open-source CFD for Enterprise
|   o   O   o    |  Version : 4.4.0
|    o     o     |  ENGYS Ltd. <http://engys.com/>
|       o        |
\*---------------------------------------------------------------------------
License
    This file is part of HELYXcore.
    HELYXcore is based on OpenFOAM (R) <http://www.openfoam.org/>.

    HELYXcore is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HELYXcore is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HELYXcore.  If not, see <http://www.gnu.org/licenses/>.

Copyright
    (c) 2011-2015 OpenFOAM Foundation
    (c) 2024 Engys Ltd.

Class
    Foam::DSMCBaseCloud

Description
    Virtual abstract base class for templated DSMCCloud

SourceFiles
    DSMCBaseCloud.C

\*---------------------------------------------------------------------------*/

#ifndef DSMCBaseCloud_H
#define DSMCBaseCloud_H

#include "fields/volFields/volFields.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                       Class DSMCBaseCloud Declaration
\*---------------------------------------------------------------------------*/

class DSMCBaseCloud
{
public:

    //- Runtime type information
    TypeName("DSMCBaseCloud");


    // Constructors

        //- Null constructor
        DSMCBaseCloud();

        //- Disallow default bitwise copy construction
        DSMCBaseCloud(const DSMCBaseCloud&) = delete;


    //- Destructor
    virtual ~DSMCBaseCloud();


    // Member Operators

        //- Disallow default bitwise assignment
        void operator=(const DSMCBaseCloud&) = delete;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
