#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/cylindricalDomainWind/* constant/triSurface/

# Mesh
helyxRun -parallel helyxHexMesh

# Check
helyxRun checkMesh -allRegions -writeAllMetrics -latestTime

# Run post-processing
helyxRun postProcess -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )' -dict system/controlDict.mesh

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch cylindricalDomainWind.foam

#------------------------------------------------------------------------------
