#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory
set -e                  # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy geometry files
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/underHoodCar/heatExchangerTable-internal-porous-radiator constant/
cp "$HELYX_TUTORIALS"/resources/geometry/underHoodCar/stl/* constant/triSurface/

# Background mesh in series
helyxRun blockMesh

# Decompose case
helyxRun decomposePar

# Mesh in parallel
helyxRun helyxHexMesh

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch underHoodCarChannel.foam

#------------------------------------------------------------------------------
