#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

# copy motorbike surface from resources folder
cp $HELYX_TUTORIALS/resources/geometry/motorBike.obj.gz constant/triSurface/
runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication decomposePar

runParallel helyxHexMesh -overwrite

runParallel createZeroDirectory

runParallel patchSummary
runParallel potentialFoam -noFunctionObjects
runParallel $(getApplication)

runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime

# -----------------------------------------------------------------------------
