#[[---------------------------------------------------------------------------]
|       o        |
|    o     o     |  HELYX (R) : Open-source CFD for Enterprise
|   o   O   o    |  Version : Dev
|    o     o     |  ENGYS Ltd. <http://engys.com/>
|       o        |
[-----------------------------------------------------------------------------]
License
    This file is part of HELYXcore.
    HELYXcore is based on OpenFOAM (R) <http://www.openfoam.org/>.

    HELYXcore is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HELYXcore is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HELYXcore.  If not, see <http://www.gnu.org/licenses/>.

Copyright
    (c) 2020 Engys Ltd.

[----------------------------------------------------------------------------]]



# Convert colourMaps to header files

set(header
"/*---------------------------------------------------------------------------*\\
|       o        |
|    o     o     |  HELYX (R) : Open-source CFD for Enterprise
|   o   O   o    |  Version : Dev
|    o     o     |  ENGYS Ltd. <http://engys.com/>
|       o        |
\\*---------------------------------------------------------------------------
License
    This file is part of HELYXcore.
    HELYXcore is based on OpenFOAM (R) <http://www.openfoam.org/>.

    HELYXcore is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HELYXcore is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HELYXcore.  If not, see <http://www.gnu.org/licenses/>.

Description
    This file is automatically generated by HELYX to enable colour maps to be
    compiled into the runTimeVisualisation functionObject.  Any changes made
    will be lost upon re-compilation.

\\*---------------------------------------------------------------------------*/
"
)

set(RTPP_VISUALISATION_DIR "${CMAKE_CURRENT_LIST_DIR}/RunTimeVisualisation")

set(
    availableColourMapsFile
    "${RTPP_VISUALISATION_DIR}/colourMaps/availableColourmaps.H"
    )
set(file_contents "")

file(WRITE ${availableColourMapsFile}
"${header}

constexpr const char * availableColourMapsCharArray = R\"\"\"\"(
availableColourMaps
{
"
)

file(GLOB input_files ${RTPP_VISUALISATION_DIR}/colourMaps/definitions/*)
list(REMOVE_ITEM input_files ${availableColourMapsFile})

foreach(input_file ${input_files})
    file(READ ${input_file} file_contents)
    string(REPLACE "\n" "\n        " file_contents "${file_contents}")
    get_filename_component(output_file ${input_file} NAME)
    file(APPEND ${availableColourMapsFile}
    "
    ${output_file}
    {
        ${file_contents}
    }
    ")
endforeach()

file(APPEND ${availableColourMapsFile}
"
}
)\"\"\"\";
"
)
