#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $HELYX_PROJECT_DIR/bin/tools/RunFunctions

# -----------------------------------------------------------------------------

application=$(getApplication)

# Create mesh
runApplication blockMesh

# Create sets
runApplication topoSet

# Create baffles and fields
runApplication createBaffles -overwrite


# -----------------------------------------------------------------------------
