#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Copy input surface from resources directory
mkdir -p constant/triSurface
cp "$HELYX_TUTORIALS"/resources/geometry/SnakeRiver/AcrossRiver.stl.gz constant/triSurface/

# Background mesh
helyxRun blockMesh

# Move dynamic mesh
helyxRun moveDynamicMesh -checkAMI

# Mesh report
helyxRun checkMesh -writeAllMetrics -latestTime
helyxRun postProcess -constant -fields '( aspectRatio determinant nonOrthogonality skewness volumeRatio )'

# Create dummy file for ParaView visualisation
touch snakeRiverCanyon.foam

#------------------------------------------------------------------------------
