#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Create mesh
helyxRun blockMesh

# Decompose mesh
helyxRun decomposePar

# Setup
helyxRun caseSetup

# Run solver without chemistry
helyxRun helyxSolve

# Create dummy file for ParaView visualisation
touch counterFlowFlame2D.foam

#------------------------------------------------------------------------------
