/*---------------------------------------------------------------------------*\
|       o        |
|    o     o     |  HELYX (R) : Open-source CFD for Enterprise
|   o   O   o    |  Version : Dev
|    o     o     |  ENGYS Ltd. <http://engys.com/>
|       o        |
\*---------------------------------------------------------------------------
License
    This file is part of HELYXcore.
    HELYXcore is based on OpenFOAM (R) <http://www.openfoam.org/>.

    HELYXcore is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    HELYXcore is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with HELYXcore.  If not, see <http://www.gnu.org/licenses/>.

Copyright
    (c) 2015-2019 OpenCFD Ltd.
    (c) 2020-2024 Engys Ltd.

Class
    Foam::functionObjects::runTimeVis::RendererExtraData

Description
    Contains information about the scene being rendered

SourceFiles
    <none>

\*---------------------------------------------------------------------------*/

#pragma once

#include "primitives/strings/fileName/fileName.H"
#include <string>

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam::functionObjects::runTimeVis
{

/*---------------------------------------------------------------------------*\
                     Struct RendererExtraData Declaration
\*---------------------------------------------------------------------------*/

struct RendererExtraData
{
public:
    std::string sceneName;
    fileName pathToOutputFileWithoutExtension;
    double currentTime;
    std::string cameraName;

    RendererExtraData(
        const std::string &sceneName,
        const fileName &pathToOutputFileWithoutExtension,
        double currentTime,
        const std::string &cameraName
    )
        : sceneName(sceneName), pathToOutputFileWithoutExtension(pathToOutputFileWithoutExtension),
          currentTime(currentTime), cameraName(cameraName)
    {};
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

// ************************************************************************* //
