#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $HELYX_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

cleanCase
\rm -rf constant/boundaryData/inlet 2>/dev/null
\rm -rf results 2>/dev/null

#------------------------------------------------------------------------------
