#!/bin/bash
cd "${0%/*}" || exit 1    # Run from this directory
set -e                    # Exit immediately if a command fails

#------------------------------------------------------------------------------

# Create mesh
helyxRun blockMesh
helyxRun decomposePar
helyxRun helyxHexMesh -overwrite
helyxRun extrudeMesh -overwrite

# Split mesh
helyxRun splitMeshRegions -zoneToRegionMap '( (pellet (pellet)) )' -overwrite

# Setup
helyxRun caseSetup

# Run
helyxRun helyxSolve

# Make linked mesh-regions so that ParaView can visualise
./Allrun.post

#------------------------------------------------------------------------------
